version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" 
      - "5672:5672"    
    networks:
      - app_network

  inventory_service:
    build:
      context: ./inventory_service
    depends_on:
      - rabbitmq
    networks:
      - app_network
    ports:
      - "8003:8001"

  order_service:
    build:
      context: ./order_service
    depends_on:
      - rabbitmq
    networks:
      - app_network
    ports:
      - "8002:8000" 

networks:
  app_network:
    driver: bridge
